# Format: {folx} can have {treats}, as a treat

# The case of these will not be changed
FOLX = [
    "Transfems",
    "Foxgirls",
    "Foxes",
    "Transmascs",
    "Catgirls",
    "Catboys",
    "Wolfgirls",
    "Wolfboys",
    "Puppygirls",
    "Dogboys",
    "Furries",
    "Ratgirls",
    "Wyverns",
    "Deergirls",
    "Cryptids",
    "I",
    "The Maus",
    "A bee",
    "Wikipedians",
    "Mathematicians",
    "CS undergrads",
    "Rust developers",
    "Javascript developers",
    "Python developers",
    "PHP developers",
    "C developers",
    "C++ developers",
    "C# developers",
    "Arch Linux users",
    "Gentoo users",
    "Nix users",
    "Debian users",
    "Windows users",
    "Mac users",
    "You",
    "Fedibots",
    "Robotgirls",
    "Dolls",
    "woem.men users",
    "woem-ers",
    "labyrinth.zone users",
    "fox.nexus users",
    "honeycomb.engineer users",
    "Yassie",
    "Yaseenists",
    "Folx that use they/them",
    "Open source maintainers",
    "Package maintainers",
    "Mastodon users",
    "Akkoma users",
    "Sharkey users",
    "Glitch-soc users",
    "GoToSocial users",
    "Firefish users",
    "Iceshrimp users",
    "Dagns",
    "Good pets",
    "Gamers",
    "Doms",
    "The Kat",
    "Polycules",
    "FFXIV players",
    "Cuties",
    "Boykissers",
    "Girlkissers",
    "Enbykissers",
    "Femboys",
    "Useless lesbians",
    "Orange cats",
    "Void kitties",
    "Everyone",
    "Nyanbinary folx",
    "Friend-shaped creatures",
    "Neurospicy people",
    "A Sammy",
    "Xenia",
    "Livvy",
    "Luna",
    "Julia",
    "Kris",
    "transfem.social users",
    "Lexi",
    "catgirl-engine users",
    "Cute dorks",
    "The BOFH",
    "Wikimedians",
    "Tim Sweeney",
    "Pastafarians",
    "Discordians",
    "Neurotypicals",
    "Vim users",
    "Emacs users",
    "Nano users",
    "Large Language Models",
    "Lost robots",
    "Scientists",
    "Subscribers",
    "Software supply chains",
    "Infosec mavens",
    "Rapid response furries",
    "Robos",
    "Drones",
    "We",
    "Omegas",
    "Alphas",
    "Queer people",
    "Debian Maintainers",
    "Debian Developers, uploading",
    "Debian Developers, non-uploading",
    "Humanoids",
    "Canids",
    "Vulpines",
    "Felines",
    "Kreechurs",
    "Optimists",
    "Pessimists",
    "Realists",
    "Grouchy sysadmins",
    "Poets",
    "The Scout from TF2",
    "The Soldier from TF2",
    "The Pyro from TF2",
    "The Demoman from TF2",
    "The Heavy from TF2",
    "The Engineer from TF2",
    "The Medic from TF2",
    "The Sniper from TF2",
    "The Spy from TF2",
    "We and our 847 partners",
    "Xbox players",
    "Playstation players",
    "PC players",
    "Nintendo players",
    "Dani",
    "Mara",
    "Rail",
    "Taavi",
    "Herobrine",
    "Linux Ricers",
    "Sackboy",
    "Robloxians",
    "Everyone in the closet",
    "Disabled people",
    "That kind person at the grocery store",
    "Critters",
    "Non-human entities",
    "Therians",
    "Nerds",
    "Dorks",
    "Cat lovers",
    "Dog lovers",
    "Gardeners",
    "Claire",
    "A random MediaWiki extension",
    "A random MediaWiki skin",
    "MediaWiki",
    "Skin:Citizen",
    "Extension:Cargo",
    "Miraheze",
]

# The case of these will not be changed
TREATS = [
    "a headpat",
    "an anti-trust lawsuit",
    "some gunpowder",
    "a misskey fork",
    "a normal fork",
    "some poorly maintained code",
    "some MediaWiki",
    "some chicken nuggets",
    "a ride on a Sprinter 158/9",
    "a ride on a Class 218",
    "a ride on an ICE 4",
    "a ride on a Stadler KISS",
    "an undefined variable",
    "a new spinny skirt",
    "a new set of thigh highs",
    "a new checked shirt",
    "new pronouns",
    "a cheemsborgar",
    "a copy of Celeste",
    "Play of the Game",
    "a cheeky Nandos",
    "a cuddle of the Yassie plushie",
    "a fediblock",
    "a broken migration",
    "some new cat ears",
    "a LEGO UCS Millennium Falcon 75192",
    "a `random.choice(TREATS)`",
    "a new OLED steamdeck",
    "a barely used Nvidia RTX 4090 Ti",
    "a LEGO UCS Death Star 75159",
    "a shiny Gardevoir",
    "an iced latte",
    "a docker container",
    "an invalid IPv4 address",
    "an IPv6 in the RFC 4193 block",
    "a **BLÅHAJ**",
    "a malformed BIRD config",
    "a *click*",
    "belly rubs",
    "working code",
    ":3",
    "a biiiiig stretch",
    "a cute frog",
    "a neofox",
    "a neocat",
    "a trip to IKEA",
    "some extra spoons",
    "a little kiss on the forehead",
    "a flatpak",
    "a cool rock",
    "some cool moss",
    "a redundant backup",
    "a fluffy tail",
    "a snoot boop",
    "a creative mode Minecraft server",
    "a hit of dopamine",
    "root access",
    "a boiled pizza",
    "a Eurasian collared dove",
    "a Monster Ultra White",
    "a Monster Ultra Rosa",
    "some bepis",
    "an unmaintained npm package",
    "a hacky python script",
    "a shitpost",
    "a Thinkpad T440p",
    "a Nix flake",
    "a Warhammer Age of Sigmar Warrior Starter Set",
    "temporary use of the single brain cell",
    "a Twitch Prime subscription",
    "a comfy blanket",
    "a hassle-free git merge",
    "a stack overflow",
    "federated biting",
    "nibbles from a maus",
    "small bits of cheese",
    "a furnished kennel",
    "a new 3D printer",
    "an extra hydrated spool of PLA",
    "a new 60% mechanical keyboard",
    "a failing wireguard tunnel",
    "broken Path MTU Discovery",
    "a 100 MB Iomega Zip Disk",
    "a nat 20",
    "an ear wiggle",
    "another fedi drama",
    "a Windows 98 VM",
    "a Torment Nexus",
    "little a Salami",
    "a little break",
    "a way to exit vim",
    "a giant pride flag",
    "spam from mastodon dot social",
    "a dependabot PR",
    "a 1996 Subaru Outback",
    "a request to agree to the GPL",
    "some extra RAM",
    "a 7200 RPM hard drive",
    "a zero-day exploit",
    "a cute little collar",
    "*this* subpost",
    "a little nap",
    "trailing commas",
    "paw beans",
    "brushy brushy",
    "walkies",
    "ear scritches",
    "a bowl of kibble",
    "a game of fetch",
    "an hour-long video about a fridge",
    "an infodump",
    "a parallel play session",
    "a new stim toy",
    "some peace and quiet",
    "a pipe bomb",
    "warm sheets fresh out of the dryer",
    "a cookie",
    "a bag of Percy Pigs",
    "a long lie-in",
    "documentation stored in a discord server",
    "SSO",
    "an LDAP server",
    "a lightly-chewed CAT6a cable",
    "a combined DisplayPort/HDMI port",
    "yet another micro-USB cable",
    "a proprietary charging port",
    "a Y2K bug",
    "a Year 2038 bug",
    "an integer overflow",
    "a keysmash",
    "free downloadable RAM",
    "a random excuse from the BOFH's excuse generator",
    "fully automated luxury gay space communism",
    "a barnstar",
    "the British Rail Advanced Passenger Train",
    "a smooth, quiet, and altogether delightful experience",
    "railway electrification",
    "a Grafana dashboard",
    "a memory leak",
    "a kernel panic",
    "a sequence from the OEIS",
    "a cuddle with a plushie",
    "a visit from a TV Licensing Enforcement Officer",
    "a nice relaxing bath",
    "a Get Out of Jail Free card",
    "a bottle of sparkly nail polish",
    "the last slice of pizza",
    "Tim Sweeney",
    "a reminder that this bot [accepts contributions](https://github.com/theresnotime/as-a-treat)",
    "a successful EU261 claim",
    "an unoccupied middle seat",
    "a Code-Review +2 vote",
    "a PGP key signature",
    "a peering request",
    "a disk failure",
    "a last-minute aircraft swap",
    "a geodesic dome",
    "an all-nighter",
    "an unterminated regular expression literal",
    "an expired SSL certificate",
    "a solarpunk utopia",
    "a giant mechanical spider",
    "a lost robot",
    "an inflatable tentacle",
    "a hacky racer",
    "several tshunks",
    "a hallucinating Large Language Model",
    "an unexpected delay repayment",
    "a weighted blanket",
    "a fully operational hoverport",
    "a juicy strawblbery",
    "a blatantly gerrymandered district",
    "a QSL request",
    "Jupyter Notebooks",
    "a Fortran code from 1976",
    "as-a-treat as a Service (aaaS)",
    "an Oxford comma",
    "a worn out VHS tape",
    "a slightly scratched laserdisc",
    "a write-protected 3½-inch floppy",
    "a suspicious USB drive",
    "a demagnetised cassette tape",
    "a spicy GitHub tarball",
    "an sshd backdoor",
    "an orphan source",
    "a new neo* emoji pack",
    "a timezone change",
    "a Potion of Invisibility",
    "Universal Basic Income",
    "an awawawawa",
    "the GitHub consequences",
    "an etherkiller",
    "a USB condom",
    "a loafing cat",
    "UTF-8",
    "UTF-32",
    "a hug",
    "this",
    "frozen yogurt",
    "a light mode theme",
    "a genuine compliment",
    "a free upgrade to premium economy",
    "a ride in the front seat of the DLR",
    "the window seat",
    "an empty table seat on the train",
    "melted frozen yoghurt",
    "a meowing backpack",
    "a Non-Maintainer Upload",
    "an FTBFS bug",
    "a source-only upload",
    "a stable point release",
    "a package in NEW",
    "a new release of the Debian Policy Manual",
    "a library transition",
    "a failed autopkgtest",
    "an inconveniently timed freeze",
    "a broken reverse dependency",
    "DM upload rights",
    "a Hetzner takedown",
    "some petty corruption",
    "a little bribery",
    "a small kickback",
    "a minor scandal",
    "corporate embezzlement",
    "tax fraud",
    "LF OS installed on their main computer",
    "a vote of support",
    "a rigged random number generator",
    "a smoking 18650 battery",
    "a long-running Jenkins job",
    "a 5-star rating and a big tip",
    "a slushie with all the flavours mixed together",
    "some gender euphoria",
    "in-cab signalling",
    "a movement authority",
    "an eurobalise",
    "variable gauge rolling stock",
    "a section of dual-gauge track",
    "an oddly-specific hyperactive interest in old, outdated software",
    "an IBM PC/AT",
    "a giant pile of dead hardware platforms",
    "corporate in-fighting",
    "a full development lifecycle reset",
    "a Blåhaj-colored computer",
    "a sentence that is false",
    "a fully-functional Commodore Amiga 1200",
    "a disk box",
    "a golden joystick",
    "negative zero",
    "a fun new meme generator",
    "the unbearable lightness of being",
    "a camping trip to Isla Sorna",
    "some mojibake",
    "one moment of perfect beauty",
    "a novel compiler bug",
    "some highland cattle",
    "an Übercharge",
    "the intelligence",
    "a briefcase",
    "the capture point",
    "a payload cart",
    "the hill",
    "hats",
    "crate keys",
    "an unusual",
    "a golden frying pan",
    "a 1.5TB LTO-5 storage tape",
    "an unsubstantiated copyright strike",
    "a sea view room",
    "an all-you-can-eat buffet",
    "a comfy hoodie",
    "a 55-gallon barrel of lube",
    "a 150kW DC rapid charger",
    "a little pot of tea",
    "a platinum trophy",
    "a custom plushie",
    "a bowl of Skittles and M&Ms mixed together",
    "the last Rolo",
    "an inaccurate commit message",
    "robux",
    "tix",
    "a singular robuck",
    "a singular ticket",
    "score bubbles",
    "prize bubbles",
    "vbucks",
    "collectabells",
    "free alternative",
    "linux rice",
    "more ram",
    "more arrays",
    "yawn detection",
    "a light switch that doesn't seem to do anything",
    "an out of control Markov bot",
    "an HR-mandated diversity and inclusion training video",
    "some new laptop stickers",
    "an unexpected package delivery",
    "a day off",
    "a vase of pretty flowers",
    "me",
    "a cute blushy face",
    "an egg",
    "a wink",
    "some new plants",
    "a shiny thing",
    "capitalism's downfall",
    "the right to grumble at leisure all day long",
    "a bite",
    "carcinisation",
    "a brand new box of floppy disks",
    "a picture frame containing a projection of everything in the universe",
    "a back rub",
    "all those meetings cancelled",
    "breakfast in bed",
    "alt text",
    "a cat making biscuits",
    "a piece of helpful advice",
    "an unexpected long weekend",
    "a ride in the front seat upstairs on a double-decker bus",
    "a CloudStrike",
    "rail renationalisation",
    "spammy push notifications",
    "a poorly described Jira ticket",
    "a squeaky toy",
    "a surprise tax rebate",
    "a little bit of pud",
    "an extra fluffy pillow",
    "a discount code for 15% off",
    "tone indicators",
    "control of the aux",
    "a reminder to like and subscribe",
    "a sponsorship from PCBWay",
    "an indecipherable compiler error",
    "a cloned Yubikey",
    "some copper from Ea-nāṣir",
    "a live service game shutdown",
    "a very non-suspicious giant wooden horse",
    "an arrow to the knee",
    "a security vulnerability",
    "a patch",
    "an XSS",
    "a SQL injection",
    "a CSRF vulnerability",
    "a fun cat fact",
]
