# Format: {folx} can have {treats}, as a treat

# The case of these will not be changed
FOLX = [
    "Transfems",
    "Foxgirls",
    "Foxes",
    "Transmascs",
    "Catgirls",
    "Catboys",
    "Wolfgirls",
    "Wolfboys",
    "Puppygirls",
    "Dogboys",
    "Furries",
    "Ratgirls",
    "Wyverns",
    "Deergirls",
    "Cryptids",
    "I",
    "The Maus",
    "Bees",
    "Wikipedians",
    "Mathematicians",
    "CS undergrads",
    "Rust developers",
    "Javascript developers",
    "Python developers",
    "PHP developers",
    "C developers",
    "C++ developers",
    "C# developers",
    "Java developers",
    "Arch Linux users",
    "Alpine Linux users",
    "Gentoo users",
    "Nix users",
    "Debian users",
    "Windows users",
    "Mac users",
    "Fedora users",
    "You",
    "Fedibots",
    "Robotgirls",
    "Dolls",
    "labyrinth.zone users",
    "fox.nexus users",
    "honeycomb.engineer users",
    "Yassie",
    "Yaseenists",
    "Folx that use they/them",
    "Open source maintainers",
    "Package maintainers",
    "Mastodon users",
    "Akkoma users",
    "Sharkey users",
    "Glitch-soc users",
    "GoToSocial users",
    "Firefish users",
    "Iceshrimp users",
    "Dagns",
    "Good pets",
    "Gamers",
    "Doms",
    "The Kat",
    "Polycules",
    "FFXIV players",
    "Cuties",
    "Boykissers",
    "Girlkissers",
    "Enbykissers",
    "Femboys",
    "Useless lesbians",
    "Orange cats",
    "Void kitties",
    "Everyone",
    "Nyanbinary folx",
    "Friend-shaped creatures",
    "Neurospicy people",
    "Sammy",
    "Xenia",
    "Livvy",
    "Luna",
    "Julia",
    "Kris",
    "Fuxle",
    "Cal",
    "transfem.social users",
    "Lexi",
    "catgirl-engine users",
    "Cute dorks",
    "The BOFH",
    "Wikimedians",
    "Tim Sweeney",
    "Pastafarians",
    "Discordians",
    "Neurotypicals",
    "Vim users",
    "Emacs users",
    "Nano users",
    "Large Language Models",
    "Lost robots",
    "Scientists",
    "Subscribers",
    "Software supply chains",
    "Infosec mavens",
    "Rapid response furries",
    "Robos",
    "Drones",
    "We",
    "Omegas",
    "Alphas",
    "Queer people",
    "Debian Maintainers",
    "Debian Developers, uploading",
    "Debian Developers, non-uploading",
    "Humanoids",
    "Canids",
    "Vulpines",
    "Felines",
    "Kreechurs",
    "Optimists",
    "Pessimists",
    "Realists",
    "Grouchy sysadmins",
    "Poets",
    "The Scout from TF2",
    "The Soldier from TF2",
    "The Pyro from TF2",
    "The Demoman from TF2",
    "The Heavy from TF2",
    "The Engineer from TF2",
    "The Medic from TF2",
    "The Sniper from TF2",
    "The Spy from TF2",
    "Demoknight mains",
    "We and our 847 partners",
    "Xbox players",
    "Playstation players",
    "PC players",
    "Nintendo players",
    "Dani",
    "Mara",
    "Rail",
    "Taavi",
    "Herobrine",
    "Sackboy",
    "Robloxians",
    "Everyone in the closet",
    "Disabled people",
    "That kind person at the grocery store",
    "Critters",
    "Non-human entities",
    "Therians",
    "No one",
    "Nerds",
    "Dorks",
    "Cat lovers",
    "Dog lovers",
    "Gardeners",
    "Claire",
    "A random MediaWiki extension",
    "A random MediaWiki skin",
    "MediaWiki",
    "Skin:Citizen",
    "Extension:Cargo",
    "Miraheze",
    "Starfleet captains",
    "Klingons",
    "Romulans",
    "Vulcans",
    "Ferengi",
    "The Borg",
    "Soong-type androids",
    "Extension:DataDump",
    "Extension:CSS",
    "Extension:CreateWiki",
    "Extension:WikiDiscover",
    "Neocats",
    "Neofoxes",
    "Cheese gobblers",
    "Disney adults",
    "IRC users",
    "ChanServ",
    "NickServ",
    "API crime committers",
    "gts.apicrim.es users",
    "Dragonfoxes",
    "Yinglets",
    "My (25M) subs (23F, 26F, 22M, 28M, 28M)",
    "Slenderman",
    "K&R",
    "Vampires",
    "D&D players",
    "The DM",
    "Madeline",
    "Part of You",
    "Readers",
    "The ouroboros",
    "Fedi users",
    "New fedi users",
    "Elf-friends",
    "Chell",
    "GLaDOS",
    "Wheatley",
    "The BDFL",
    "Lucas",
    "Hobbits",
    "Fedi meta",
    "Medi feta",
    "The Steam catgirl",
    "XMPP users",
    "Hackers",
    "OpenStreetMap contributors",
    "Discordian popes",
    "Chat",
    "Moths",
    "Grown-ups",
    "People who work from home",
    "The bots",
    "That one",
    "Blåhajar",
    "liv",
    "Your Innie",
    "Your Outie",
    "The Smol",
    "Hackerspaces",
    "Beepers",
    "Computer touchers",
    "SCP-085",
    "Bouba",
    "Kiki",
    "Monsterdon",
    "As a Treat bot contributors",
    "GPN attendees",
    "OpenStack Swift administrators",
    "catgirls of the .[center|cloud|global] variety",
    "Blue",
    "Jade",
    "The treats bot",
    "NTSC video",
    "Kittens",
    "Spherical cow in a vacuum",
    "Ducks",
    "Quackers",
]

# The case of these will not be changed
TREATS = [
    "a headpat",
    "nothing",
    "an anti-trust lawsuit",
    "some gunpowder",
    "a misskey fork",
    "a normal fork",
    "some poorly maintained code",
    "some MediaWiki",
    "some chicken nuggets",
    "a ride on a Sprinter 158/9",
    "a ride on a Class 218",
    "a ride on an ICE 4",
    "a ride on a Stadler KISS",
    "an undefined variable",
    "a new spinny skirt",
    "a new set of thigh highs",
    "a new checked shirt",
    "new pronouns",
    "a cheemsborgar",
    "a copy of Celeste",
    "Play of the Game",
    "a cheeky Nandos",
    "a cuddle of the Yassie plushie",
    "a fediblock",
    "a broken migration",
    "some new cat ears",
    "a LEGO UCS Millennium Falcon 75192",
    "a `random.choice(TREATS)`",
    "a new OLED steamdeck",
    "a barely used Nvidia RTX 4090 Ti",
    "a LEGO UCS Death Star 75159",
    "a shiny Gardevoir",
    "an iced latte",
    "a docker container",
    "an invalid IPv4 address",
    "an IPv6 in the RFC 4193 block",
    "a **BLÅHAJ**",
    "a malformed BIRD config",
    "a *click*",
    "belly rubs",
    "working code",
    ":3",
    "a biiiiig stretch",
    "a cute frog",
    "a neofox",
    "a neocat",
    "a trip to IKEA",
    "some extra spoons",
    "a little kiss on the forehead",
    "a flatpak",
    "a cool rock",
    "some cool moss",
    "a redundant backup",
    "a fluffy tail",
    "a snoot boop",
    "a creative mode Minecraft server",
    "a hit of dopamine",
    "root access",
    "a boiled pizza",
    "a Eurasian collared dove",
    "a Monster Ultra White",
    "a Monster Ultra Rosa",
    "some bepis",
    "an unmaintained npm package",
    "a hacky python script",
    "a shitpost",
    "a Thinkpad T440p",
    "a Nix flake",
    "a Warhammer Age of Sigmar Warrior Starter Set",
    "temporary use of the single brain cell",
    "a Twitch Prime subscription",
    "a comfy blanket",
    "a hassle-free git merge",
    "a stack overflow",
    "federated biting",
    "nibbles from a maus",
    "small bits of cheese",
    "a furnished kennel",
    "a new 3D printer",
    "an extra hydrated spool of PLA",
    "a new 60% mechanical keyboard",
    "a failing wireguard tunnel",
    "broken Path MTU Discovery",
    "a 100 MB Iomega Zip Disk",
    "a nat 20",
    "an ear wiggle",
    "another fedi drama",
    "a Windows 98 VM",
    "a Torment Nexus",
    "little a Salami",
    "a little break",
    "a way to exit vim",
    "a giant pride flag",
    "spam from mastodon dot social",
    "a dependabot PR",
    "a 1996 Subaru Outback",
    "a request to agree to the GPL",
    "some extra RAM",
    "a 7200 RPM hard drive",
    "a zero-day exploit",
    "a cute little collar",
    "*this* subpost",
    "a little nap",
    "trailing commas",
    "paw beans",
    "brushy brushy",
    "walkies",
    "ear scritches",
    "a bowl of kibble",
    "a game of fetch",
    "an hour-long video about a fridge",
    "an infodump",
    "a parallel play session",
    "a new stim toy",
    "some peace and quiet",
    "a pipe bomb",
    "warm sheets fresh out of the dryer",
    "a cookie",
    "a bag of Percy Pigs",
    "a long lie-in",
    "documentation stored in a discord server",
    "SSO",
    "an LDAP server",
    "a lightly-chewed CAT6a cable",
    "a combined DisplayPort/HDMI port",
    "yet another micro-USB cable",
    "a proprietary charging port",
    "a Y2K bug",
    "a Year 2038 bug",
    "an integer overflow",
    "a keysmash",
    "free downloadable RAM",
    "a random excuse from the BOFH's excuse generator",
    "fully automated luxury gay space communism",
    "a barnstar",
    "the British Rail Advanced Passenger Train",
    "a smooth, quiet, and altogether delightful experience",
    "railway electrification",
    "a Grafana dashboard",
    "a memory leak",
    "a kernel panic",
    "a sequence from the OEIS",
    "a cuddle with a plushie",
    "a visit from a TV Licensing Enforcement Officer",
    "a nice relaxing bath",
    "a Get Out of Jail Free card",
    "a bottle of sparkly nail polish",
    "the last slice of pizza",
    "Tim Sweeney",
    "a reminder that this bot [accepts contributions](https://github.com/theresnotime/as-a-treat)",
    "a successful EU261 claim",
    "an unoccupied middle seat",
    "a Code-Review +2 vote",
    "a PGP key signature",
    "a peering request",
    "a disk failure",
    "a last-minute aircraft swap",
    "a geodesic dome",
    "an all-nighter",
    "an unterminated regular expression literal",
    "an expired SSL certificate",
    "a solarpunk utopia",
    "a giant mechanical spider",
    "a lost robot",
    "an inflatable tentacle",
    "a hacky racer",
    "several tshunks",
    "a hallucinating Large Language Model",
    "an unexpected delay repayment",
    "a weighted blanket",
    "a fully operational hoverport",
    "a juicy strawblbery",
    "a blatantly gerrymandered district",
    "a QSL request",
    "Jupyter Notebooks",
    "a Fortran code from 1976",
    "as-a-treat as a Service (aaaS)",
    "an Oxford comma",
    "a worn out VHS tape",
    "a slightly scratched laserdisc",
    "a write-protected 3½-inch floppy",
    "a suspicious USB drive",
    "a demagnetised cassette tape",
    "a spicy GitHub tarball",
    "an sshd backdoor",
    "an orphan source",
    "a new neo* emoji pack",
    "a timezone change",
    "a Potion of Invisibility",
    "Universal Basic Income",
    "an awawawawa",
    "the GitHub consequences",
    "an etherkiller",
    "a USB condom",
    "a loafing cat",
    "UTF-8",
    "UTF-32",
    "a hug",
    "this",
    "frozen yogurt",
    "a light mode theme",
    "a genuine compliment",
    "a free upgrade to premium economy",
    "a ride in the front seat of the DLR",
    "the window seat",
    "an empty table seat on the train",
    "melted frozen yoghurt",
    "a meowing backpack",
    "a Non-Maintainer Upload",
    "an FTBFS bug",
    "a source-only upload",
    "a stable point release",
    "a package in NEW",
    "a new release of the Debian Policy Manual",
    "a library transition",
    "a failed autopkgtest",
    "an inconveniently timed freeze",
    "a broken reverse dependency",
    "DM upload rights",
    "a Hetzner takedown",
    "some petty corruption",
    "a little bribery",
    "a small kickback",
    "a minor scandal",
    "corporate embezzlement",
    "tax fraud",
    "LF OS installed on their main computer",
    "a vote of support",
    "a rigged random number generator",
    "a smoking 18650 battery",
    "a long-running Jenkins job",
    "a 5-star rating and a big tip",
    "a slushie with all the flavours mixed together",
    "some gender euphoria",
    "in-cab signalling",
    "a movement authority",
    "an eurobalise",
    "variable gauge rolling stock",
    "a section of dual-gauge track",
    "an oddly-specific hyperactive interest in old, outdated software",
    "an IBM PC/AT",
    "a giant pile of dead hardware platforms",
    "corporate in-fighting",
    "a full development lifecycle reset",
    "a Blåhaj-colored computer",
    "a sentence that is false",
    "a fully-functional Commodore Amiga 1200",
    "a disk box",
    "a golden joystick",
    "negative zero",
    "a fun new meme generator",
    "the unbearable lightness of being",
    "a camping trip to Isla Sorna",
    "some mojibake",
    "one moment of perfect beauty",
    "a novel compiler bug",
    "some highland cattle",
    "an Übercharge",
    "the intelligence",
    "a briefcase",
    "the capture point",
    "a payload cart",
    "the hill",
    "hats",
    "crate keys",
    "an unusual",
    "a golden frying pan",
    "a 1.5TB LTO-5 storage tape",
    "an unsubstantiated copyright strike",
    "a sea view room",
    "an all-you-can-eat buffet",
    "a comfy hoodie",
    "a 55-gallon barrel of lube",
    "a 150kW DC rapid charger",
    "a little pot of tea",
    "a platinum trophy",
    "a custom plushie",
    "a bowl of Skittles and M&Ms mixed together",
    "the last Rolo",
    "an inaccurate commit message",
    "robux",
    "tix",
    "a singular robuck",
    "a singular ticket",
    "score bubbles",
    "prize bubbles",
    "vbucks",
    "collectabells",
    "free alternative",
    "linux rice",
    "more ram",
    "more arrays",
    "yawn detection",
    "a light switch that doesn't seem to do anything",
    "an out of control Markov bot",
    "an HR-mandated diversity and inclusion training video",
    "some new laptop stickers",
    "an unexpected package delivery",
    "a day off",
    "a vase of pretty flowers",
    "me",
    "a cute blushy face",
    "an egg",
    "a wink",
    "some new plants",
    "a shiny thing",
    "capitalism's downfall",
    "the right to grumble at leisure all day long",
    "a bite",
    "carcinisation",
    "a brand new box of floppy disks",
    "a picture frame containing a projection of everything in the universe",
    "a back rub",
    "all those meetings cancelled",
    "breakfast in bed",
    "alt text",
    "a cat making biscuits",
    "a piece of helpful advice",
    "an unexpected long weekend",
    "a ride in the front seat upstairs on a double-decker bus",
    "a CloudStrike",
    "rail renationalisation",
    "spammy push notifications",
    "a poorly described Jira ticket",
    "a squeaky toy",
    "a surprise tax rebate",
    "a little bit of pud",
    "an extra fluffy pillow",
    "a discount code for 15% off",
    "tone indicators",
    "control of the aux",
    "a reminder to like and subscribe",
    "a sponsorship from PCBWay",
    "an indecipherable compiler error",
    "a cloned Yubikey",
    "some copper from Ea-nāṣir",
    "a live service game shutdown",
    "a very non-suspicious giant wooden horse",
    "an arrow to the knee",
    "a security vulnerability",
    "a patch",
    "an XSS",
    "a SQL injection",
    "a CSRF vulnerability",
    "a fun cat fact",
    "a warp core breach",
    "a new Monster of the Week",
    "membership in the Federation",
    "subspace interference",
    "a bowl of Gagh",
    "an emotion chip",
    "36 bars of gold-pressed Latinum",
    "a path traversal",
    "a Framework",
    "estrogen",
    "testosterone",
    "Extra Magic Hours",
    "a Lightning Lane Multi Pass",
    "a souvenir bucket of popcorn",
    "a Loungefly mini backpack",
    "a mouse ear headband",
    "a baked Camembert",
    "a rubber ducky",
    "a '; DROP TABLE users; --",
    "an in-show exit",
    "a segmentation fault",
    "a friday afternoon PagerDuty alert",
    "some freshly baked bread",
    "a 642 episode let's play series",
    "a 210 minute queue for a roller coaster",
    "double pepperoni",
    "a quip",
    "op",
    "voice",
    "a ThinkPad X230",
    "a pointless button",
    "Speedy Boarding",
    "the next turn on the Xbox",
    "updated terms and conditions",
    "the front row on a roller coaster",
    "the back row on a roller coaster",
    "a 6€ hot chocolate",
    "a jigsaw puzzle with a piece missing",
    "my home assistant login",
    "my mastodon password",
    "a home assistant integration",
    "a working backup",
    "a broken backup",
    "a full disk",
    "an empty disk",
    "posixly correct coreutils",
    "a PNG corrupted in an interesting way",
    "a major version upgrade",
    "a bugfix",
    "a bug",
    "a useless machine",
    "a proof of the Riemann hypothesis",
    "a proof that P≠NP",
    "a proof that P=NP",
    "a constructive proof that P=NP",
    "a non-constructive proof that P=NP",
    "three positive integers a, b, c such that a^n + b^n = c^n for an n > 2",
    "a glass of choccy milk",
    "a union",
    "a union job",
    "a NullPointerException",
    "[object Object]",
    "a Protogen",
    "the Protogens",
    "a Synth",
    "the Synths",
    "umbreon",
    "a cutie",
    "a pizza",
    "some free candy",
    "a printer that just works",
    "a reminder to follow this bot",
    "a pair of programming socks",
    "an HO scale LNER A4 class 4-6-2 locomotive",
    "a slack message that just says hi",
    "a 7-day global Interrail pass",
    "a mysterious envelope",
    "a pair of woolly socks",
    "some Python 2 code",
    "some Java 7 code",
    "another jq implementation",
    "a pair of programmer socks",
    "an LED strip",
    "a LED strip",
    "an ad hoc, informally-specified, bug-ridden, slow implementation of half of Common Lisp",
    "an IPv4 block",
    "a Rubik's Cube",
    "a warm fuzzy feeling",
    "a configure script",
    "cow tools",
    "a copy of K&R",
    "a forwarded meme",
    "a chain email",
    "a new browser engine",
    "a stroopwafel",
    "a public piano",
    "a conlang",
    "a pile of unread books",
    "a hello world program",
    "a quine",
    "a polyglot program",
    "a fun task",
    "an introduction post",
    "a man page that points to an info page",
    "some manually written troff markup",
    "an unmaintained tool",
    "tasty leftovers",
    "a smolhaj",
    "a portal gun",
    "an Aperture Science Handheld Portal Device",
    "a Companion Cube",
    "a god object",
    "an eepy cat",
    "a Silmaril",
    "a messenger from Godot",
    "second breakfast",
    "a Safe and Sophie Germain prime number",
    "a cellular automata",
    "a prime number p greater than 127, such that r=2ᵖ-1 and p=2ʳ-1 are both prime",
    "a proof to the Collatz Conjecture",
    "1 (one) virus",
    "a TARDIS key",
    "a beesechurger",
    "beans",
    "a trout",
    "a Ferrero Rocher",
    "Nutella",
    "a Juicero Press",
    "a cardboard box",
    "a copy of Euro Truck Simulator 2",
    "the gender fluid",
    "a gender",
    "catgirl HRT",
    "catboy HRT",
    "a scented candle",
    "one more lane",
    "a gTLD",
    "a forklift certification",
    "a postage stamp",
    "an IKEA pencil",
    "some Toblerone",
    "an insecure VNC server",
    "a little schadenfreude",
    "a cookie banner",
    "a fursuit",
    "an on-time train",
    "a unit test",
    "a seal of approval",
    "an idle fancy",
    "an SSD",
    "a retro computer",
    "a layer of untouched snow",
    "Half-Life 3",
    "a lava lamp",
    "a snow day",
    "a new furry mascot",
    "exactly 3 Scritches",
    "an ASN",
    "a car running gotosocial",
    "a 9.8 CVE",
    "an artisinally crafted ice cream sundae",
    "a super intelligent immortal snail",
    "a LEGO GBC module",
    "an RMC conversion",
    "the exit row",
    "the tenth pitch drop",
    "a flip dot display",
    "DOOM running on a random device",
    "an asteroid impact",
    "a puppy",
    "a flower from a sweetie",
    "a large correctly-formatted data file",
    "floor time",
    "two Ns",
    "the Pizza Planet truck",
    "a cameo from someone that no one has ever heard of",
    "a line of foxes waiting for chocolate",
    "plot armour",
    "a deus ex machina",
    "Chekhov's gun",
    "a surprise twist",
    "subtle foreshadowing",
    "a girlfriend",
    "a partner",
    "a boyfriend",
    "a stable Arch install",
    "🔑 Unable to decrypt message",
    "a Wellness Session",
    "a hall pass",
    "some scary numbers",
    "reintegration",
    "a Music Dance Experience",
    "an ORTBO",
    "a banger hypercore compilation",
    "a filthy af 199-bpm track",
    "mediawiki vulnerabilities",
    "a random podium inspection",
    "trains",
    "a ppc64el-specific bug",
    "an armhf-specific bug",
    "a s390x-specific bug",
    "a single /64 IPv6 prefix delegation",
    "/48 IPv6 address block",
    "an answer that only raises further questions",
    "unlimited breadsticks",
    "a fox onesie",
    "50 GiB of garbage in /nix/store",
    "a little cry",
    "a promotion",
    "thermal runaway",
    "DRS activation",
    "a wug",
    "two wugs",
    "greebles",
    "a spelling reform",
    "a live service roadmap",
    "a broken beta",
    "an account on a friend's Navidrome instance",
    "a proper kaiju film",
    "20mg confidence",
    "a corrupted thumbnail container database",
    "a reliable Deutsche Bahn connection",
    "a bottle of Mate",
    "a Tschunk",
    "colder temperatures",
    "a new 88x31px button",
    "multiple overtakes by DB Fernverkehr",
    "broken wall outlets while on a train",
    "Karlsruhe",
    "a blobcat plushie for [debugging purposes](https://en.wikipedia.org/wiki/Rubber_duck_debugging)",
    "mate in 3",
    "a breath of fresh air",
    "a flash of inspiration",
    "a heisenbug",
    "a christmas special",
    "a human-time lord metacrisis",
    "a sideloaded app",
    "some obvious ragebait",
    "an incomprehensible regex",
    "a PR with 810 changed files",
    "a new profile picture",
    "a court summons",
    "inconsistently applied internationalization and localisation logic",
    "inconsistently applied internationalisation and localization logic",
    "525 scanlines",
    "garlic",
    "a British thermal unit defined in metric",
    "a ha'penny bit",
    "an excess baggage charge",
    "a feature drop",
    "long bacon",
]
