# Format: {folx} can have {treats}, as a treat

# The case of these will not be changed
FOLX = [
    "Transfems",
    "Foxgirls",
    "Foxes",
    "Transmascs",
    "Catgirls",
    "I",
    "The Maus",
    "A bee",
    "Wikipedians",
    "Rust developers",
    "Arch Linux users",
    "You",
    "Fedibots",
    "Robotgirls",
    "Dolls",
    "woem.men users",
    "meow.woem.cat users",
    "woem-ers",
    "labyrinth.zone users",
    "Yassie",
    "Yasseenists",
    "Folx that use they/them",
    "Open source maintainers",
    "Mastodon users",
    "Akkoma users",
    "Sharkey users",
    "Glitch-soc users",
    "GoToSocial users",
    "Firefish users",
    "Iceshrimp users",
    "Dagns",
    "Good pets",
    "Gamers",
    "Doms",
    "The Kat",
    "Polycules",
    "A Mae",
    "FFXIV players",
]

# The case of these will not be changed
TREATS = [
    "a headpat",
    "an anti-trust lawsuit",
    "some gunpowder",
    "a misskey fork",
    "a normal fork",
    "some poorly maintained code",
    "some MediaWiki",
    "some chicken nuggets",
    "a ride on a Sprinter 158/9",
    "a ride on a Class 218",
    "a ride on an ICE 4",
    "a ride on a Stadler KISS",
    "an undefined variable",
    "a new spinny skirt",
    "a new set of thigh highs",
    "new pronouns",
    "a cheemsborgar",
    "a copy of Celeste",
    "play of the game",
    "a cheeky Nandos",
    "a cuddle of the Yassie plushie",
    "a fediblock",
    "a broken migration",
    "some new cat ears",
    "a LEGO UCS Millennium Falcon 75192",
    "a random.choice(TREATS)",
    "a new OLED steamdeck",
    "a barely used Nvidia RTX 4090 Ti",
    "a LEGO UCS Death Star 75159",
    "a shiny Gardevoir",
    "an iced latte",
    "a docker container",
    "an invalid IPv4 address",
    "an IPv6 in the RFC 4193 block",
    "a **BLÅHAJ**",
    "a malformed BIRD config",
    "a *click*",
    "belly rubs",
    "working code",
    ":3",
    "a biiiiig stretch",
    "a cute frog",
    "a neofox",
    "a neocat",
    "a trip to IKEA",
    "some extra spoons",
    "a little kiss on the forehead",
    "a flatpak",
    "a cool rock",
    "some cool moss",
    "a redundant backup",
    "a fluffy tail",
    "a little boop",
    "a creative mode Minecraft server",
    "a hit of dopamine",
    "root access",
    "a boiled pizza",
    "a Eurasian collared dove",
    "a Monster Ultra White",
    "a Monster Ultra Rosa",
    "some bepis",
    "an unmaintained npm package",
    "a hacky python script",
    "a shitpost",
    "a Thinkpad T440p",
    "a Nix flake",
    "a Warhammer Age of Sigmar Warrior Starter Set",
    "temporary use of the single brain cell",
    "a Twitch Prime subscription",
    "a comfy blanket",
    "a hassle-free git merge",
    "a stack overflow",
    "federated biting",
    "a 100 MB Iomega Zip Disk",
]
