name: 'Update readme count'

permissions:
  contents: write # Permission to create commits
  checks: write # Permission to trigger checks

on: workflow_dispatch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cp config.example.py config.py
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get combination count
        id: get-count
        run: echo "count=$(python gen.py -c)" >> $GITHUB_OUTPUT
      - name: Update readme
        run:
          python update_readme_count.py "${{ steps.get-count.outputs.count }}"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Add updated count to readme'
